apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ift4
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: ift4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ift4
    spec:
      containers:
        - image: ilyakuz26/ift2:v1
          name: ift2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "1000Mi"
            limits:
              cpu: "50m"
              memory: "1000Mi"
