apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-ift4
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: ift4
  template:
    metadata:
      labels:
        app: ift4
    spec:
      containers:
        - image: ilyakuz26/ift2:v1
          name: ift2
          ports:
            - containerPort: 80
